# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JapbRxI2yfU8O8hYCgVWd5cu4-8qwL-Y
"""

c=input("Enter a character").lower()

if c in 'aeiou':
  print("c is a vowel")
else:
  print("c is a consonant")